= Omni Docker + Podman Project
Sean Gilligan <https://github.com/msgilligan>
v0.0.3
:description: Omni Docker README document.
:omnidocker-version: 0.0.3

[WARNING]
This software is EXPERIMENTAL software for **REGTEST and TESTNET TRANSACTIONS** only. *USE ON MAINNET AT YOUR OWN RISK.*

[CAUTION]
This is pre-release software and APIs may change without notice.

== Omni Containers for Docker + Podman

Docker tools for Omni Core (and eventually) other Omni Components.

== Public Repository on Docker Hub

See https://hub.docker.com/repository/docker/omnilayer/omnicored (requires login)

== Quick Test/Demo of latest Omni Core docker image

`docker run --rm --name omni-demo -it omnilayer/omnicored:latest -version`

== Recommended Podman Setup on Debian Bookworm

* `sudo apt install -y podman podman-docker`
* `sudo echo 'unqualified-search-registries = ["docker.io"]' > /etc/containers/registries.conf.d/unqualified-dockerhub.conf`

== Credits

* Thanks to https://github.com/ruimarinho[@ruimarinho] for https://github.com/ruimarinho/docker-bitcoin-core[ruimarinho/docker-bitcoin-core] which
 was used as a starting point for our Omni Core Dockerfile.
