version: '3.9'

#
# Base Docker Compose file for running OmniProxy and Omni Core.
#
# Use the correct provided "override file" for the desired network.
# regtest: docker-compose.override.yml   (the default)
# testnet: docker-compose.testnet.yml
# regtest: docker-componse.mainnet.yml
#
# Run `run-compose.sh` after editing `sample.env` for a "quick start"
#

services:
  omnicore:
    image: omnilayer/omnicored:$OMNICORE_TAG
    restart: "no"
    volumes:
      - ./bitcoin-data-dir:/home/bitcoin/.bitcoin
    environment:
      OMNICORE_TAG:
      RPCUSER:
      RPCPASSWORD:
      ZMQ_BLOCK_PORT:
      ZMQ_HASH_PORT:
  omniproxy:
    image: consensusj/btcproxyd:$BTCPROXY_TAG
    restart: "no"
    ports:
      - 8080:$BTCPROXY_HTTP_PORT
    volumes:
      - ./omniproxy:/etc/btcproxyd
    environment:
      BTCPROXY_TAG:
      BTCPROXY_HTTP_PORT:
      MICRONAUT_CONFIG_FILES:
      BTCPROXYD_RPCPROXY_USERNAME: $RPCUSER
      BTCPROXYD_RPCPROXY_PASSWORD: $RPCPASSWORD
    depends_on:
      - omnicore
    links:
      - omnicore:omnicore

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.18.0.1/16
