version: '3.3'

#
# Override settings for Mainnet
# Specifies the correct ports, command-line options for Omni Core, and the configuration YAML 
# file for btcproxyd.
#

services:
  omnicore:
    ports:
      - 8332:8332
      - 8333:8333
      - ${ZMQ_BLOCK_PORT:-28332}:${ZMQ_BLOCK_PORT:-28332}
      - ${ZMQ_TX_PORT:-28333}:${ZMQ_TX_PORT:-28333}
    command:
      -printtoconsole
      -debug=1
      -txindex=1
      -rpcserialversion=0
      -addresstype=legacy
      -listenonion=false
      -zmqpubrawblock=tcp://0.0.0.0:${ZMQ_BLOCK_PORT:-28332}
      -zmqpubhashblock=tcp://0.0.0.0:${ZMQ_BLOCK_PORT:-28332}
      -zmqpubrawtx=tcp://0.0.0.0:${ZMQ_TX_PORT:-28333}
      -zmqpubhashtx=tcp://0.0.0.0:${ZMQ_TX_PORT:-28333}
      -rpcallowip=172.18.0.1/16
      -rpcbind=0.0.0.0
      -rpcuser=$RPCUSER
      -rpcpassword=$RPCPASSWORD
  omniproxy:
    environment:
      MICRONAUT_CONFIG_FILES: /etc/btcproxyd/proxy-omni-mainnet.yml
