= OmniProxy Docker Compose Configuration

== Quick Start (RegTest)

. Edit `sample.env`
. Make sure `OMICORE_TAG` and `BTCPROXY_TAG` set to correct and/or latest versions.
. `cp sample.env .env`

=== Use docker-compose directly

This approach uses the default configuration files `docker-compose.yml` and `docker-compose.override.yml`.

. `docker-compose up --detach`

=== Use the run-compose.sh script

This approach uses the configuration files `docker-compose.yml` with an "override" `.yml` file selected
based upon the network parameter (`regtest`, `mainnet`, or `testnet`) that is passed to the script. The
script also dynamically generates the `RPCPASSWORD` setting.

. `./run-compose.sh regtest`


NOTE:: That `.env` is in the `.gitignore` file, so you can make your changes there and not worry about
accidentally checking in your configuration.

== Mainnet and Testnet Status

Mainnet and Testnet configurations are not yet officially supported with Docker Compose. There
are a few things that need to be done:

1. Verify OmniProxy (`btcproxyd`) can work with a blockchain that is still syncing.

